version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      -mvn clean package
  post_build:
    commands:
      - echo Build Completed Successfully
artifacts:
  files:
    - target/spring-boot.jar
  discard-paths: yes
      